version: '3'

services:
  some-scylla:
    image: scylladb/scylla
    container_name: elain-syclla

  some-scylla2:
    image: scylladb/scylla
    container_name: elain-scylla2
    command: --seeds=elain-scylla

  some-scylla3:
    image: scylladb/scylla
    container_name: elain-scylla3
    command: --seeds=elain-scylla
